"""initial codeloom schema

Revision ID: 11ab7fb936e5
Revises: 
Create Date: 2026-02-15 17:19:23.033215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11ab7fb936e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('last_active', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_language', sa.String(length=50), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('total_lines', sa.Integer(), nullable=True),
    sa.Column('ast_status', sa.String(length=20), nullable=False),
    sa.Column('asg_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index('idx_user_projects', 'projects', ['user_id', 'created_at'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_roles_role', 'user_roles', ['role_id'], unique=False)
    op.create_index('idx_user_roles_user', 'user_roles', ['user_id'], unique=False)
    op.create_table('code_files',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('project_id', 'file_path', name='uq_project_file_path')
    )
    op.create_index('idx_code_files_project', 'code_files', ['project_id'], unique=False)
    op.create_table('conversations',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index('idx_project_conversations', 'conversations', ['project_id', 'timestamp'], unique=False)
    op.create_index('idx_session_conversations', 'conversations', ['session_id', 'timestamp'], unique=False)
    op.create_index('idx_user_conversations', 'conversations', ['user_id', 'timestamp'], unique=False)
    op.create_table('migration_plans',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_project_id', sa.UUID(), nullable=True),
    sa.Column('target_brief', sa.Text(), nullable=False),
    sa.Column('target_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_phase', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['source_project_id'], ['projects.project_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index('idx_migration_plans_project', 'migration_plans', ['source_project_id'], unique=False)
    op.create_index('idx_migration_plans_user', 'migration_plans', ['user_id'], unique=False)
    op.create_table('project_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_level', sa.String(length=20), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_access_project', 'project_access', ['project_id'], unique=False)
    op.create_index('idx_project_access_user', 'project_access', ['user_id'], unique=False)
    op.create_table('query_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_query_logs_project', 'query_logs', ['project_id', 'timestamp'], unique=False)
    op.create_index('idx_query_logs_timestamp', 'query_logs', ['timestamp'], unique=False)
    op.create_index('idx_query_logs_user', 'query_logs', ['user_id', 'timestamp'], unique=False)
    op.create_table('code_units',
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('unit_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('qualified_name', sa.String(length=1024), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('docstring', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['code_files.file_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_index('idx_code_units_file', 'code_units', ['file_id'], unique=False)
    op.create_index('idx_code_units_name', 'code_units', ['name'], unique=False)
    op.create_index('idx_code_units_project', 'code_units', ['project_id'], unique=False)
    op.create_index('idx_code_units_type', 'code_units', ['unit_type'], unique=False)
    op.create_table('migration_phases',
    sa.Column('phase_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=False),
    sa.Column('phase_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('output_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['migration_plans.plan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('phase_id'),
    sa.UniqueConstraint('plan_id', 'phase_number', name='uq_plan_phase')
    )
    op.create_index('idx_migration_phases_plan', 'migration_phases', ['plan_id'], unique=False)
    op.create_table('code_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_unit_id', sa.UUID(), nullable=False),
    sa.Column('target_unit_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.String(length=50), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_unit_id'], ['code_units.unit_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_unit_id'], ['code_units.unit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'source_unit_id', 'target_unit_id', 'edge_type', name='uq_code_edge')
    )
    op.create_index('idx_code_edges_project', 'code_edges', ['project_id'], unique=False)
    op.create_index('idx_code_edges_source', 'code_edges', ['source_unit_id'], unique=False)
    op.create_index('idx_code_edges_target', 'code_edges', ['target_unit_id'], unique=False)
    op.create_index('idx_code_edges_type', 'code_edges', ['edge_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_code_edges_type', table_name='code_edges')
    op.drop_index('idx_code_edges_target', table_name='code_edges')
    op.drop_index('idx_code_edges_source', table_name='code_edges')
    op.drop_index('idx_code_edges_project', table_name='code_edges')
    op.drop_table('code_edges')
    op.drop_index('idx_migration_phases_plan', table_name='migration_phases')
    op.drop_table('migration_phases')
    op.drop_index('idx_code_units_type', table_name='code_units')
    op.drop_index('idx_code_units_project', table_name='code_units')
    op.drop_index('idx_code_units_name', table_name='code_units')
    op.drop_index('idx_code_units_file', table_name='code_units')
    op.drop_table('code_units')
    op.drop_index('idx_query_logs_user', table_name='query_logs')
    op.drop_index('idx_query_logs_timestamp', table_name='query_logs')
    op.drop_index('idx_query_logs_project', table_name='query_logs')
    op.drop_table('query_logs')
    op.drop_index('idx_project_access_user', table_name='project_access')
    op.drop_index('idx_project_access_project', table_name='project_access')
    op.drop_table('project_access')
    op.drop_index('idx_migration_plans_user', table_name='migration_plans')
    op.drop_index('idx_migration_plans_project', table_name='migration_plans')
    op.drop_table('migration_plans')
    op.drop_index('idx_user_conversations', table_name='conversations')
    op.drop_index('idx_session_conversations', table_name='conversations')
    op.drop_index('idx_project_conversations', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_code_files_project', table_name='code_files')
    op.drop_table('code_files')
    op.drop_index('idx_user_roles_user', table_name='user_roles')
    op.drop_index('idx_user_roles_role', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('idx_user_projects', table_name='projects')
    op.drop_table('projects')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('embedding_config')
    # ### end Alembic commands ###
