"""add raptor columns to code_files

Revision ID: 2d144d33226a
Revises: 11ab7fb936e5
Create Date: 2026-02-15 20:03:01.099251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d144d33226a'
down_revision: Union[str, None] = '11ab7fb936e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_files', sa.Column('raptor_status', sa.String(length=20), nullable=True))
    op.add_column('code_files', sa.Column('raptor_error', sa.Text(), nullable=True))
    op.add_column('code_files', sa.Column('raptor_built_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_files', 'raptor_built_at')
    op.drop_column('code_files', 'raptor_error')
    op.drop_column('code_files', 'raptor_status')
    # ### end Alembic commands ###
