"""add accuracy columns to migration_plans

Revision ID: 2e7dbe92a6af
Revises: b2c3d4e5f6a7
Create Date: 2026-03-05 09:13:33.217782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e7dbe92a6af'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop legacy embedding tables if they exist (safe on both fresh and migrated DBs)
    op.execute("DROP INDEX IF EXISTS data_embeddings_embedding_idx")
    op.execute("DROP INDEX IF EXISTS embeddings_idx_1")
    op.execute("DROP INDEX IF EXISTS idx_embeddings_node_type")
    op.execute("DROP INDEX IF EXISTS idx_embeddings_project_id")
    op.execute("DROP INDEX IF EXISTS idx_embeddings_source_id")
    op.execute("DROP INDEX IF EXISTS idx_embeddings_unique_text_project")
    op.execute("DROP TABLE IF EXISTS data_embeddings")
    op.execute("DROP INDEX IF EXISTS data_data_embeddings_embedding_idx")
    op.execute("DROP INDEX IF EXISTS data_embeddings_idx_1")
    op.execute("DROP INDEX IF EXISTS idx_data_embeddings_node_type")
    op.execute("DROP INDEX IF EXISTS idx_data_embeddings_project_id")
    op.execute("DROP INDEX IF EXISTS idx_data_embeddings_source_id")
    op.execute("DROP INDEX IF EXISTS idx_data_embeddings_unique_text_project")
    op.execute("DROP TABLE IF EXISTS data_data_embeddings")
    op.add_column('migration_plans', sa.Column('accuracy_score', sa.Float(), nullable=True))
    op.add_column('migration_plans', sa.Column('accuracy_fixed_score', sa.Float(), nullable=True))
    op.add_column('migration_plans', sa.Column('accuracy_fixes_applied', sa.Integer(), nullable=True))
    op.add_column('migration_plans', sa.Column('accuracy_fixes_pending', sa.Integer(), nullable=True))
    op.add_column('migration_plans', sa.Column('accuracy_report_md', sa.Text(), nullable=True))
    op.add_column('migration_plans', sa.Column('accuracy_per_mvp', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('migration_plans', sa.Column('accuracy_last_run', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('migration_plans', 'accuracy_last_run')
    op.drop_column('migration_plans', 'accuracy_per_mvp')
    op.drop_column('migration_plans', 'accuracy_report_md')
    op.drop_column('migration_plans', 'accuracy_fixes_pending')
    op.drop_column('migration_plans', 'accuracy_fixes_applied')
    op.drop_column('migration_plans', 'accuracy_fixed_score')
    op.drop_column('migration_plans', 'accuracy_score')
    op.create_table('data_data_embeddings',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('data_data_embeddings_pkey'))
    )
    op.create_index(op.f('idx_data_embeddings_unique_text_project'), 'data_data_embeddings', [sa.literal_column('md5(text::text)'), sa.literal_column("(metadata_ ->> 'project_id'::text)")], unique=True)
    op.create_index(op.f('idx_data_embeddings_source_id'), 'data_data_embeddings', [sa.literal_column("(metadata_ ->> 'source_id'::text)")], unique=False)
    op.create_index(op.f('idx_data_embeddings_project_id'), 'data_data_embeddings', [sa.literal_column("(metadata_ ->> 'project_id'::text)")], unique=False)
    op.create_index(op.f('idx_data_embeddings_node_type'), 'data_data_embeddings', [sa.literal_column("(metadata_ ->> 'node_type'::text)")], unique=False)
    op.create_index(op.f('data_embeddings_idx_1'), 'data_data_embeddings', [sa.literal_column("(metadata_ ->> 'ref_doc_id'::text)")], unique=False)
    op.create_index(op.f('data_data_embeddings_embedding_idx'), 'data_data_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('data_embeddings',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('data_embeddings_pkey'))
    )
    op.create_index(op.f('idx_embeddings_unique_text_project'), 'data_embeddings', [sa.literal_column('md5(text::text)'), sa.literal_column("(metadata_ ->> 'project_id'::text)")], unique=True)
    op.create_index(op.f('idx_embeddings_source_id'), 'data_embeddings', [sa.literal_column("(metadata_ ->> 'source_id'::text)")], unique=False)
    op.create_index(op.f('idx_embeddings_project_id'), 'data_embeddings', [sa.literal_column("(metadata_ ->> 'project_id'::text)")], unique=False)
    op.create_index(op.f('idx_embeddings_node_type'), 'data_embeddings', [sa.literal_column("(metadata_ ->> 'node_type'::text)")], unique=False)
    op.create_index(op.f('embeddings_idx_1'), 'data_embeddings', [sa.literal_column("(metadata_ ->> 'ref_doc_id'::text)")], unique=False)
    op.create_index(op.f('data_embeddings_embedding_idx'), 'data_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
